name: CI build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode -T2.0C clean verify
      - name: Assemble coder coverage report
        run: mvn jacoco:report
      - name: Upload code coverage data to codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./**/target/site/jacoco/jacoco.xml